language: python
python:
  - 3.4
  - 3.5
matrix:
  fast_finish: true
  allow_failures:
    - python: nightly
sudo: false
addons:
  apt:
    packages:
      - install-info
cache:
  directories:
    - $HOME/.cache/pip
install: pip install tox coveralls codecov
before_script:
  # Make sure the actual install-info binary is first in PATH since
  # Debian-based distros use a wrapper script that outputs warnings and
  # breaks the info file merge trigger test.
  - mkdir texinfo
  - ln -s /usr/bin/ginstall-info texinfo/install-info
  - export PATH=$PWD/texinfo:$PATH
script: tox -e travis
after_success:
  # upload coverage data
  - pushd .tox/travis/lib/python*/site-packages
  - coveralls
  - codecov
  - popd
